import Bannner from '@/components/Bannner'
import CardList from '@/components/CardList'
import Navbar from '@/components/Navbar'
import Head from 'next/head'
import Image from 'next/image'


export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Navbar/>
        <div className='relative min-h-screen'>
          <Bannner/>
          <div  className = 'absolute top-[50%]   w-full bg-slate-200' >
            <CardList data={data}/>
          </div>
          
        </div>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const rsp = await fetch('https://fakestoreapi.com/products')
  const data = await rsp.json()

  return{
    props:{
      data
    }
  }
}